# -*- coding: utf-8 -*-
"""Analyse of Flights

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/104XSaYMvHi-9Y9DE7r-ePMLMWmD1yqS_
"""

import pandas as pd
from scipy import stats

import tensorflow as tf
tf.test.gpu_device_name()

from google.colab import files
uploaded = files.upload()

data = pd.read_csv('flights.csv')

data.head

data.mean()

data['arr_delay'].mean()

stats.trim_mean(data['arr_delay'], 0.1)

data['arr_delay'].std()

data['arr_delay'].median()

data['arr_delay'].mode()

data['arr_delay'].hist()

data['arr_delay'].hist(bins=100)

data['arr_delay'][data['arr_delay']<100].hist(bins=80)